plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: base64
title: Base64
description: Encode and decode data using the base64 alphabet.
version: 1.1.2
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/base64
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
tags:
- base64
- encoder
- decoder
- utilities
hub_tags:
  use_cases: [data_utility]
  keywords: [base64, encoder, decoder, utilities]
  features: []
actions:
  encode:
    title: Encoder
    description: Encode data to Base64
    input:
      content2:
        type: string
        description: Atest
        required: true
    output:
      data1:
        title: Encoded Data
        type: bytes
      data2:
        title: Encoded Data
        type: bytes
  decode:
    title: Decoder
    description: Decode Base64 to data
    input:
      base6434:
        type: bytes
        description:
        required: true
      errors:
        type: string
        description: How errors should be handled when decoding Base64
        default: nothing
        enum:
        - replace
        - ignore
        - nothing
        required: false
    output:
      data:
        title: Decoded Data
        type: string
  decode_with_array:
    title: Decoder with Array
    description: Decode Base64 to data
    input:
      base64_array33:
        type: "[]string"
        required: true
        example: ['MQ==', "Mg=="]
    output:
      data:
        title: Decoded Data
        description: Decoded data result
        type: string
        required: true
  decode_with_test7:
    title: Decoder with Test
    input:
      base64_array3:
        type: "[]string"
        required: true
        example: ['MQ==', "Mg=="]
    output:
      data:
        title: Decoded Data
        description: Decoded data result
        type: string
        required: true
  decode_with_test_second:
    title: Decoder with Test Second
    description: Test
    output:
      data3:
        title: Decoded Data
        description:
        type: string
        required: true
triggers:
  decode_with_test:
    title: Decoder with Test
    input:
      base64_array4:
        type: "[]string"
        required: true
        example: ['MQ==', "Mg=="]
    output:
      data:
        title: Decoded Data
        description: Decoded data result
        type: string
        required: true
