plugin_spec_version: v2
extension: plugin
products: ["insightconnect"]
name: microsoft_office365_email
title: Microsoft Office 365 Email
description: The Microsoft Office 365 email plugin enables phishing analysis and email management. The plugin includes the ability to manage and remediate suspicious email
version: 5.0.5
vendor: rapid7
support: rapid7
status: []
resources:
  vendor_url: https://www.microsoft.com/
  docs_url: https://docs.rapid7.com/insightconnect/office365/
tags:
- Microsoft
- Email
- Message
- Office 365
hub_tags:
  use_cases: [threat_detection_and_response, alerting_and_notifications]
  keywords: [microsoft, email, office365]
  features: []

types:
  header:
    name:
      type: string
      required: false
    value:
      type: string
      required: false

  attachment_file:
    file_name:
      type: string
      required: false
    content:
      type: string
      required: false
    content_type:
      type: string
      required: false

  attachment_email_nested_two:
    id:
      type: string
      title: ID
      required: false
    sender:
      type: string
      required: false
    subject:
      type: string
      required: false
    body:
      type: string
      required: false
    categories:
      type: '[]string'
      required: false
    headers:
      type: '[]header'
      required: false
    attached_files:
      type: '[]attachment_file'
      required: false
    attached_emails:
      type: '[]object'
      required: false
    account:
      type: string
      required: false
    recipients:
      type: "[]string"
      required: false
    has_attachments:
      type: boolean
      required: false

  attachment_email_nested:
    id:
      type: string
      title: ID
      required: false
    sender:
      type: string
      required: false
    subject:
      type: string
      required: false
    body:
      type: string
      required: false
    categories:
      type: '[]string'
      required: false
    headers:
      type: '[]header'
      required: false
    attached_files:
      type: '[]attachment_file'
      required: false
    attached_emails:
      type: '[]attachment_email_nested_two'
      required: false
    account:
      type: string
      required: false
    recipients:
      type: "[]string"
      required: false
    has_attachments:
      type: boolean
      required: false

  attachment_email:
    id:
      type: string
      title: ID
      required: false
    sender:
      type: string
      required: false
    subject:
      type: string
      required: false
    body:
      type: string
      required: false
    categories:
      type: '[]string'
      required: false
    headers:
      type: '[]header'
      required: false
    attached_files:
      type: '[]attachment_file'
      required: false
    attached_emails:
      type: '[]attachment_email_nested'
      required: false
    account:
      type: string
      required: false
    recipients:
      type: "[]string"
      required: false
    has_attachments:
      type: boolean
      required: false

  icon_email:
    id:
      type: string
      title: ID
      required: false
    account:
      type: string
      title: Account
      required: false
      description: Account for which the email was found on
    is_read:
      type: boolean
      title: Is Read
      required: false
      description: Whether or not the email has been read
    sender:
      type: string
      required: false
    subject:
      type: string
      required: false
    body:
      type: string
      required: false
    attached_files:
      type: '[]attachment_file'
      required: false
    attached_emails:
      type: '[]attachment_email'
      required: false
    flattened_attached_emails:
      type: '[]attachment_email'
      required: false
    flattened_attached_files:
      type: '[]attachment_file'
      required: false
    categories:
      type: '[]string'
      required: false
    headers:
      type: '[]header'
      required: false
    recipients:
      type: "[]string"
      required: false
    has_attachments:
      type: boolean
      required: false

connection:
  tenant_id:
    title: Tenant ID
    description: The ID of the directory that identifies the tenant
    type: string
    required: true
    example: b12abc12-abcd-abcd-abcd-3ac2dz8e9z2g
  app_id:
    title: App ID
    description: The ID of the registered app that obtained the refresh token
    type: string
    required: true
    example: b12abc12-abcd-abcd-abcd-3ac2dz8e9z2g
  app_secret:
    title: App Secret
    description: The secret of the registered app that obtained the refresh token
    type: credential_secret_key
    required: true
    example: '{"secretKey": "9de5069c5afe602b2ea0a04b66beb2c0" }'

triggers:
  email_received:
    title: Email Received
    description: Poll mailbox for new email
    input:
      mailbox_id:
        title: Mailbox ID
        type: string
        description: The mailbox to monitor for incoming email
        example: user@example.com
        required: true
      folder_name:
        title: Folder Name
        type: string
        description: Common values are Calendar, Trash, Drafts, Inbox, Outbox, Sent,
          Junk, Tasks, Contacts. You can also use a completely custom value, for example
          python_mailing_list. Mailbox names are case-sensitive. Folder GUID may be specified as well
        example: Inbox
        required: false
      interval:
        title: Interval
        type: integer
        description: "How often to poll for new email in seconds"
        default: 15
        example: 15
        required: false
      subject_query:
        title: Subject Query
        type: string
        description: Query to search for in subject (regex capable). Only these email will activate this trigger
        default: ''
        example: You have a new message
        required: false
      flatten_attachments:
        title: Flatten Attachments
        type: boolean
        description: Will return all attachments as flat lists instead of nested emails
        required: true
        example: false
        default: false
    output:
      icon_email:
        title: Email
        type: icon_email
        required: false
        description: Email
  folder_modified:
    title: Email Added to Folder
    description: Monitor folder for added emails
    input:
      mailbox_id:
        title: Mailbox ID
        type: string
        description: The mailbox to monitor for new email
        example: user@example.com
        required: true
      folder_name:
        title: Folder Name
        type: string
        description: Common values are Calendar, Trash, Drafts, Inbox, Outbox, Sent,
          Junk, Tasks, Contacts. You can also use a completely custom value, for example
          python_mailing_list or a folder GUID. Mailbox names are case-sensitive
        example: Inbox
        required: true
      interval:
        title: Interval
        type: integer
        description: "How often to poll for new email in seconds"
        default: 15
        example: 15
        required: false
      subject_query:
        title: Subject Query
        type: string
        description: Query to search for in subject (regex capable). Only these email will activate this trigger
        default: ''
        example: You have a new message
        required: false
      flatten_attachments:
        title: Flatten Attachments
        type: boolean
        description: Will return all attachments as flat lists instead of nested emails
        required: true
        example: false
        default: false

    output:
      icon_email:
        title: Email
        type: icon_email
        required: false
        description: Email
actions:
  get_email_from_user:
    title: Get Email from User
    description: Get a list of emails from a user's mailbox matching search terms
    input:
      mailbox_id:
        title: Mailbox ID
        type: string
        description: Target user to retrieve email from
        example: user@example.com
        required: true
      max_number_to_return:
        title: Max Number to Return
        type: integer
        default: 250
        description: Maximum number of emails to return. Max limit is 250 (default)
        example: 250
        required: true
      from_contains:
        title: From
        type: string
        description: From address contains this (can be full e-mail address or just a domain) e.g. user@example.com or example.com
        example: example.com
        required: false
      subject_contains:
        title: Subject
        type: string
        description: Subject contains this word or phrase
        example: Free
        required: false
      body_contains:
        title: Body
        type: string
        description: Body contains this word or phrase
        example: Click here
        required: false
    output:
      email_list:
        title: Email List
        type: '[]icon_email'
        description: List of emails
        required: false
  delete_email:
    title: Delete Email
    description: Delete an email by ID
    input:
      email_id:
        title: Email ID
        type: string
        description: ID of email to delete
        example: AAMkADI3Mzc1ZTg3LTIzYWEtNDNmNI1hZDQ5LTBiMjAyY5A3ZThhYwBGAAAAAAAxDvrQc8q6SqGLTJ9iB-SGBwC8UQDN7ObVSLWQuxHJ-dDTAAAAAAEJAAC8UQDN7ObVSLWQuxHJ-dDTAAHPCj-HAAA=
        required: true
      mailbox_id:
        title: Mailbox ID
        type: string
        description: User mailbox ID to delete from
        example: user@example.com
        required: true
    output:
      success:
        title: Success
        type: boolean
        description: Was delete successful
        required: true
  move_email:
    title: Move Email
    description: Move an email to a destination folder
    input:
      mailbox_id:
        title: Mailbox ID
        description: Mailbox ID
        example: user@example.com
        type: string
        required: true
      email_id:
        title: Email ID
        description: The email ID to retrieve
        example: AAMkADI3Mzc1ZTg3LTIzYWEtNDNmNI1hZDQ5LTBiMjAyY5A3ZThhYwBGAAAAAAAxDvrQc8q6SqGLTJ9iB-SGBwC8UQDN7ObVSLWQuxHJ-dDTAAAAAAEJAAC8UQDN7ObVSLWQuxHJ-dDTAAHPCj-HAAA=
        type: string
        required: true
      folder_name:
        title: Folder Name
        description: The destination folder name
        example: Inbox
        type: string
        required: true
    output:
      success:
        title: Success
        type: boolean
        description: Was move successful
        required: false
  send_email:
    title: Send Email
    description: Send an email
    input:
      email_from:
        type: string
        title: Email Sender
        description: Email address this email will be sent from
        example: user@example.com
        required: true
        order: 1
      email_to:
        type: "[]string"
        title: Email To
        description: One or more email addresses of recipients
        example: ["user@example.com", "user2@example.com"]
        required: true
        order: 2
      subject:
        title: Subject
        type: string
        description: Subject of the email
        example: Alert from InsightConnect
        required: true
        order: 3
      body:
        title: Body
        type: string
        description: Body of the email
        example: The workflow succeeded
        required: true
        order: 4
      is_html:
        title: Is HTML
        type: boolean
        description: Is the body of this email HTML
        example: false
        required: true
        order: 5
      bcc:
        title: BCC
        type: '[]string'
        description: Blind carbon copy recipients
        example: ['user@example.com', 'user@example.com']
        order: 6
        required: false
      cc:
        title: CC
        type: '[]string'
        description: Carbon copy recipients
        example: ['user@example.com', 'user@example.com']
        order: 7
        required: false
      attachment:
        title: Attachment
        type: "[]file"
        description: Accepts one or more attachment represented as a file type which contains the filename and the file content encoded with base64
        example: '[{"filename": "setup.exe", "content": "UmFwaWQ3IEluc2lnaHRDb25uZWN0Cg=="}]'
        order: 8
        required: false
    output:
      success:
        title: Success
        type: boolean
        description: Success
        required: true
