# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Decode Base64 to data"


class Input:
    BASE64_ARRAY = "base64_array"
    

class Output:
    DATA = "data"
    

class DecodeWithArrayInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "base64_array": {
      "type": "array",
      "title": "Base64 Array",
      "description": "Data to decode",
      "items": {
        "type": "string"
      },
      "order": 1
    }
  },
  "required": [
    "base64_array"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DecodeWithArrayOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "data": {
      "type": "string",
      "title": "Decoded Data",
      "description": "Decoded data result",
      "order": 1
    }
  },
  "required": [
    "data"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
